version: '3'
services:
  neo4j:
    image: neo4j:4.4.10-enterprise
    hostname: neo4j
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data

    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: neo4j/contrelspawn123
      NEO4JLABS_PLUGINS: '["apoc"]'